<?php
// Automatically Generated by TestLink Installer - Fri, 17 Aug 18 04:26:41 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'repol99');
define('DB_PASS', '12345678');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
